# Generated by Django 2.0.4 on 2018-05-02 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('begin', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('begin', models.DateField(blank=True, null=True)),
                ('availability_type', models.CharField(choices=[('DATE', 'date'), ('STRING', 'string')], default='STRING', max_length=64)),
                ('availability_date', models.DateField(blank=True, null=True)),
                ('availability_string', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('duration', models.CharField(max_length=255)),
                ('begin', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CV.Company')),
            ],
            options={
                'ordering': ['-begin'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CV.Cv')),
            ],
        ),
        migrations.CreateModel(
            name='MissionFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('order', models.IntegerField()),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CV.Experience')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MissionTechnical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024)),
                ('order', models.IntegerField()),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CV.Experience')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Skill categories',
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CV.SkillCategory'),
        ),
        migrations.AddField(
            model_name='skill',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CV.Cv'),
        ),
        migrations.AddField(
            model_name='company',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CV.Cv'),
        ),
    ]
