# Generated by Django 2.0.5 on 2018-05-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
