# Generated by Django 2.1.1 on 2018-09-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0003_auto_20180504_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website_link',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
