# Generated by Django 2.1.1 on 2018-09-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0004_auto_20180903_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='availability_string',
        ),
        migrations.AddField(
            model_name='cv',
            name='availability_offset_number',
            field=models.IntegerField(blank=True, help_text="if 'Availability type' is 'offset'", null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='availability_offset_quantity',
            field=models.CharField(choices=[('DAY', 'day'), ('MONTH', 'month')], default='MONTH', help_text="if 'Availability type' is 'offset'", max_length=64),
        ),
        migrations.AlterField(
            model_name='cv',
            name='availability_date',
            field=models.DateField(blank=True, help_text="if 'Availability type' is 'at'", null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='availability_type',
            field=models.CharField(choices=[('NOW', 'now'), ('OFFSET', 'offset'), ('AT', 'at')], default='NOW', max_length=64),
        ),
    ]
